# Generated by Django 2.1.5 on 2019-02-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spendoApp', '0002_auto_20190217_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
                ('medida', models.CharField(default=False, max_length=15)),
                ('costos_adicionales', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spendoApp.Categories')),
            ],
        ),
        migrations.RemoveField(
            model_name='registro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='user',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spendoApp.TicketType'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spendoApp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions_level',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AddField(
            model_name='register',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spendoApp.User'),
        ),
    ]
